name: CI

on:
  push:
    branches: [ libretro ]

jobs:
  build_mxe_32:
    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v2
    - name: Init submodules
      run: git submodule update --init

    - name: Install deps
      run: sudo apt-get install
        ninja-build

    - name: Set up MXE environment
      run: |
        wget 'https://github.com/realnc/mxe/releases/download/binary/mxe.tar.gz'
        sudo tar xf mxe.tar.gz -C /opt
        rm mxe.tar.gz

    - name: Build
      run: |
        source /opt/mxe/mxe-env.sh
        cd libretro
        CC=gcc make platform=win TARGET_TRIPLET="i686-w64-mingw32.static" BUNDLED_AUDIO_CODECS=0 BUNDLED_LIBSNDFILE=0 WITH_DYNAREC=x86 deps
        CC=gcc make platform=win TARGET_TRIPLET="i686-w64-mingw32.static" BUNDLED_AUDIO_CODECS=0 BUNDLED_LIBSNDFILE=0 WITH_DYNAREC=x86 -j`nproc`
        i686-w64-mingw32.static-strip dosbox_core_libretro.dll
        zip -9 windows-x86.zip dosbox_core_libretro.dll

    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: windows-x86.zip
        path: libretro/windows-x86.zip

  build_mxe_64:
    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v2
    - name: Init submodules
      run: git submodule update --init

    - name: Install deps
      run: sudo apt-get install
        ninja-build

    - name: Set up MXE environment
      run: |
        wget 'https://github.com/realnc/mxe/releases/download/binary/mxe.tar.gz'
        sudo tar xf mxe.tar.gz -C /opt
        rm mxe.tar.gz

    - name: Build
      run: |
        source /opt/mxe/mxe-env.sh
        cd libretro
        CC=gcc make platform=win TARGET_TRIPLET="x86_64-w64-mingw32.static" BUNDLED_AUDIO_CODECS=0 BUNDLED_LIBSNDFILE=0 WITH_DYNAREC=x86_64 deps
        CC=gcc make platform=win TARGET_TRIPLET="x86_64-w64-mingw32.static" BUNDLED_AUDIO_CODECS=0 BUNDLED_LIBSNDFILE=0 WITH_DYNAREC=x86_64 -j`nproc`
        x86_64-w64-mingw32.static-strip dosbox_core_libretro.dll
        zip -9 windows-x64.zip dosbox_core_libretro.dll

    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: windows-x64.zip
        path: libretro/windows-x64.zip

  build_linux_64:
    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v2
    - name: Init submodules
      run: git submodule update --init

    - name: Install deps
      run: sudo apt-get install
        libsdl-net1.2-dev
        ninja-build

    - name: Build
      run: |
        cd libretro
        make CC=gcc-9 CXX=g++-9 STATIC_LIBCXX=1 WITH_DYNAREC=x86_64 deps
        make CC=gcc-9 CXX=g++-9 STATIC_LIBCXX=1 WITH_DYNAREC=x86_64 -j`nproc`
        strip dosbox_core_libretro.so
        zip -9 linux-x64.zip dosbox_core_libretro.so

    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: linux-x64.zip
        path: libretro/linux-x64.zip

  upload_build:
    runs-on: ubuntu-16.04
    needs: [build_mxe_32, build_mxe_64, build_linux_64]

    steps:
    - uses: actions/download-artifact@v1
      with:
        name: windows-x64.zip
    - uses: actions/download-artifact@v1
      with:
        name: windows-x86.zip
    - uses: actions/download-artifact@v1
      with:
        name: linux-x64.zip

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest_build"
        prerelease: true
        title: "Latest Build"
        files: |
          windows-x64.zip
          windows-x86.zip
          linux-x64.zip
