name: CI

on:
  push:
    branches: [ libretro ]

jobs:
  build_msys2_64:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Init submodules
      run: git submodule update --init

    - name: Setup Msys2 environment
      uses: numworks/setup-msys2@v1
      with:
        msystem: MINGW64
        update: true

    # Update again. Needed to actually get all updates.
    - name: Update msys2
      run: msys2do pacman --noconfirm -Syuu

    - name: Install deps
      run: msys2do pacman --noconfirm -S --needed
        base-devel
        git
        mingw-w64-x86_64-SDL_net
        mingw-w64-x86_64-cmake
        mingw-w64-x86_64-glib2
        mingw-w64-x86_64-libsndfile
        mingw-w64-x86_64-ninja
        mingw-w64-x86_64-toolchain
        zip

    - name: Build
      run: |
        cd libretro
        msys2do ./github_msys2_build.sh
        msys2do zip -9 windows-x64.zip dosbox_core_libretro.dll

    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: windows-x64.zip
        path: libretro/windows-x64.zip

  build_msys2_32:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Init submodules
      run: git submodule update --init

    - name: Setup Msys2 environment
      uses: numworks/setup-msys2@v1
      with:
        msystem: MINGW32
        update: true

    # Update again. Needed to actually get all updates.
    - name: Update msys2
      run: msys2do pacman --noconfirm -Syuu

    - name: Install deps
      run: msys2do pacman --noconfirm -S --needed
        base-devel
        git
        mingw-w64-i686-SDL_net
        mingw-w64-i686-cmake
        mingw-w64-i686-glib2
        mingw-w64-i686-libsndfile
        mingw-w64-i686-ninja
        mingw-w64-i686-toolchain
        zip

    - name: Build
      run: |
        cd libretro
        msys2do ./github_msys2_build.sh
        msys2do zip -9 windows-x86.zip dosbox_core_libretro.dll

    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: windows-x86.zip
        path: libretro/windows-x86.zip

  build_linux_64:
    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v2
    - name: Init submodules
      run: git submodule update --init

    - name: Install deps
      run: sudo apt-get install
        libsdl-net1.2-dev
        ninja-build

    - name: Build
      run: |
        cd libretro
        make CC=gcc-9 CXX=g++-9 STATIC_LIBCXX=1 WITH_DYNAREC=x86_64 deps
        make CC=gcc-9 CXX=g++-9 STATIC_LIBCXX=1 WITH_DYNAREC=x86_64 -j`nproc`
        strip dosbox_core_libretro.so
        zip -9 linux-x64.zip dosbox_core_libretro.so

    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: linux-x64.zip
        path: libretro/linux-x64.zip

  upload_build:
    runs-on: ubuntu-16.04
    needs: [build_msys2_64, build_msys2_32, build_linux_64]

    steps:
    - uses: actions/download-artifact@v1
      with:
        name: windows-x64.zip
    - uses: actions/download-artifact@v1
      with:
        name: windows-x86.zip
    - uses: actions/download-artifact@v1
      with:
        name: linux-x64.zip

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest_build"
        prerelease: true
        title: "Latest Build"
        files: |
          windows-x64.zip
          windows-x86.zip
          linux-x64.zip
